name: MobileUseMultiAgent

agent:
    name: MobileUseAgent
    args:
      agent_config:

        type: MultiAgent

        vlm:
          model_name: qwen2.5-vl-72b-instruct
          api_key: xxxxx
          base_url: xxxxx
          max_tokens: 1024
          temperature: 0

        operator:
          enabled: true
          name: Operator
          prompt_config: operator.yaml
          # # To enable proactive exlporation, enable the following config.
          # # See mobile_use/utils/proactive_exploration/README.md for more details.
          # knowledge: 
          #   explored_knowledge_path: <path-to-explored-knowledge-json-file>

        answer_agent:
          enabled: true
          name: AnswerAgent
          prompt_config: answer_agent.yaml
          # # To enable proactive exlporation, enable the following config.
          # # See mobile_use/utils/proactive_exploration/README.md for more details.
          # knowledge: 
          #   explored_knowledge_path: <path-to-explored-knowledge-json-file>

        reflector:
          enabled: true

        trajectory_reflector:
          enabled: true

        global_reflector:
          enabled: true

        progressor:
          enabled: true

        # # To enable Reflection-on-Demand, enable the following config.
        # # You may need to adjust the reflection threshold.
        # reflect_on_demand: true
        # logprob_threshold: -0.001


task:
  class: MobileUse_AutoTest
  args:
    save_dir: "./logs/evaluation_mobile_use"
    max_rounds: 25
    request_interval: 3

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060
